[tool.poetry]
version = "1.0.0"
name = "wtf-coronavirus-ohio"
description = "A WTF dashboard module for coronavirus data from ODH"
authors = ["Taylor D. Edmiston <tedmiston@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests-html = "^0.10.0"
requests-cache = "^0.5.2"
mypy = "^0.770"
pydantic = "^1.7.3"

[tool.poetry.dev-dependencies]
black = {version = "*", allow-prereleases = true}
coverage = "*"
pytest = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
