[tool.poetry]
name = "wtf-covid-19-ohio"
version = "1.0.0"
description = "A WTF (wtfutil) dashboard module for the COVID-19 data from the Ohio Department of Health"
authors = ["Taylor D. Edmiston <tedmiston@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests-html = "^0.10.0"
requests-cache = "^0.5.2"
mypy = "^0.770"

[tool.poetry.dev-dependencies]
black = {version = "*", allow-prereleases = true}
coverage = "*"
pytest = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
