name: CI

on:
  push:
    branches: '**'
    tags:
      - v1*
  pull_request:
    branches: [ master ]

jobs:

  build:
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.13

    - name: Install
      run: |
        pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Lint
      run: make format-check mypy

    - name: Unit Tests
      run: |
        make test
        poetry run coverage xml

    - name: Codecov
      uses: codecov/codecov-action@v3

    - name: Docker Build
      run: make build

    - name: Docker Test
      run: make test-docker

    - name: Run
      run: make run-docker

    - name: Publish
      if: github.ref == 'refs/heads/master'
      run: make push
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Publish
      run: make build push -- TAG=${GITHUB_REF##*/}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
