name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: poetry install
    - name: Build
      run: make build
    - name: Test
      run: make format-check mypy test coverage
    - name: Run
      run: make run
    - name: Push
      if: github.ref == 'refs/heads/master'
      run: make push
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
